###project 1. Mercedes-Benz Greener Manufacturing

In [2]:
# importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import LabelEncoder

In [10]:
# loading datasets of both train and test 
train=pd.read_csv('/content/train.csv', index_col='ID')
test=pd.read_csv('/content/test.csv',index_col='ID')

In [11]:
train.head()

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
0,130.81,k,v,at,a,d,u,j,o,0,...,0,0,1,0,0,0,0,0,0,0
6,88.53,k,t,av,e,d,y,l,o,0,...,1,0,0,0,0,0,0,0,0,0
7,76.26,az,w,n,c,d,x,j,x,0,...,0,0,0,0,0,0,1,0,0,0
9,80.62,az,t,n,f,d,x,l,e,0,...,0,0,0,0,0,0,0,0,0,0
13,78.02,az,v,n,f,d,h,d,n,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# shape of train data
train.shape

(4209, 377)

In [13]:
test.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
1,az,v,n,f,d,t,a,w,0,0,...,0,0,0,1,0,0,0,0,0,0
2,t,b,ai,a,d,b,g,y,0,0,...,0,0,1,0,0,0,0,0,0,0
3,az,v,as,f,d,a,j,j,0,0,...,0,0,0,1,0,0,0,0,0,0
4,az,l,n,f,d,z,l,n,0,0,...,0,0,0,1,0,0,0,0,0,0
5,w,s,as,c,d,y,i,m,0,0,...,1,0,0,0,0,0,0,0,0,0

#### unique values

In [14]:
# checking for dtype for all columns
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4209 entries, 0 to 8417
Columns: 377 entries, y to X385
dtypes: float64(1), int64(368), object(8)
memory usage: 12.1+ MB

In [15]:
for col in train.columns:
  if(train[col].dtype != np.float64 and train[col].dtype != np.int64):
    unique_train=train[col].unique().tolist()
    unique_test=test[col].unique().tolist()

    for member in unique_test:
      if member not in unique_train:
        unique_train.append(member)

    #applying labelencoder
    le=LabelEncoder()  
    le.fit(list(train[col].values) + list(train[col].values))
    train[col] = le.transform(list(train[col].values))
    unique_value_train = train[col].unique().tolist()
    le.fit(list(test[col].values) + list(test[col].values))
    test[col] = le.transform(list(test[col].values))
    unique_value_test = test[col].unique().tolist()

In [16]:
print(unique_value_train)

[14, 23, 4, 13, 18, 0, 7, 15, 12, 10, 3, 8, 21, 9, 1, 16, 22, 6, 24, 11, 5, 20, 17, 19, 2]

In [17]:
train.head()

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
0,130.81,32,23,17,0,3,24,9,14,0,...,0,0,1,0,0,0,0,0,0,0
6,88.53,32,21,19,4,3,28,11,14,0,...,1,0,0,0,0,0,0,0,0,0
7,76.26,20,24,34,2,3,27,9,23,0,...,0,0,0,0,0,0,1,0,0,0
9,80.62,20,21,34,5,3,27,11,4,0,...,0,0,0,0,0,0,0,0,0,0
13,78.02,20,23,34,5,3,12,3,13,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
test.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
1,21,23,34,5,3,26,0,22,0,0,...,0,0,0,1,0,0,0,0,0,0
2,42,3,8,0,3,9,6,24,0,0,...,0,0,1,0,0,0,0,0,0,0
3,21,23,17,5,3,0,9,9,0,0,...,0,0,0,1,0,0,0,0,0,0
4,21,13,34,5,3,31,11,13,0,0,...,0,0,0,1,0,0,0,0,0,0
5,45,20,17,2,3,30,8,12,0,0,...,1,0,0,0,0,0,0,0,0,0

###Variance Threshold

In [19]:
# for any variance in column in train data=0 should be removed
var_thres_train=VarianceThreshold(threshold=0)
var_thres_train.fit(train)

VarianceThreshold(threshold=0)

In [20]:
var_zero_train=[column for column in train.columns
if column not in train.columns[var_thres_train.get_support()]]

In [21]:
# dropping columns with zero variance in axis=1
train.drop(var_zero_train, axis=1, inplace=True)

In [22]:
train.head()

,y,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
0,130.81,32,23,17,0,3,24,9,14,0,...,0,0,1,0,0,0,0,0,0,0
6,88.53,32,21,19,4,3,28,11,14,0,...,1,0,0,0,0,0,0,0,0,0
7,76.26,20,24,34,2,3,27,9,23,0,...,0,0,0,0,0,0,1,0,0,0
9,80.62,20,21,34,5,3,27,11,4,0,...,0,0,0,0,0,0,0,0,0,0
13,78.02,20,23,34,5,3,12,3,13,0,...,0,0,0,0,0,0,0,0,0,0

### checking for null values

In [23]:
train.isnull().sum()

y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 365, dtype: int64

In [24]:
# droping for zero variance for testdata
test.drop(var_zero_train,axis = 1,inplace = True)
test.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,,,,,,,,,,,,,,,,,,,,,
1,21,23,34,5,3,26,0,22,0,0,...,0,0,0,1,0,0,0,0,0,0
2,42,3,8,0,3,9,6,24,0,0,...,0,0,1,0,0,0,0,0,0,0
3,21,23,17,5,3,0,9,9,0,0,...,0,0,0,1,0,0,0,0,0,0
4,21,13,34,5,3,31,11,13,0,0,...,0,0,0,1,0,0,0,0,0,0
5,45,20,17,2,3,30,8,12,0,0,...,1,0,0,0,0,0,0,0,0,0

In [25]:
#checking null for test data
test.isnull().sum()

X0      0
X1      0
X2      0
X3      0
X4      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 364, dtype: int64

In [26]:
print(train.shape, test.shape)

(4209, 365) (4209, 364)

### scaling

In [27]:
X_train = train.iloc[:,1:]
y_train = train.iloc[:,0]

from sklearn.preprocessing import StandardScaler
scalling = StandardScaler()
X_train_scalled = scalling.fit_transform(X_train)
test_scalled = scalling.fit_transform(test)

### Dimensional Reduction

In [29]:
# using PCA estimators
from sklearn.decomposition import PCA

In [30]:
sklearn_PCA = PCA(n_components = 200)

In [31]:
sklearn_PCA.fit(X_train_scalled)
x_train_transform = sklearn_PCA.transform(X_train_scalled)
print(x_train_transform.shape)

(4209, 200)

In [32]:
#simillarly applying PCA for testdata
x_test_transform = sklearn_PCA.transform(test_scalled)

In [33]:
sklearn_PCA.components_

array([[-5.35850147e-02,  3.02768146e-02,  7.67089079e-02, ...,
         2.54830761e-03, -1.03542621e-03, -3.83323362e-03],
       [-4.40293464e-02,  7.64543717e-02,  3.03300345e-02, ...,
        -6.26757593e-03, -1.08513170e-04,  2.65683265e-03],
       [-7.54999549e-02,  1.10395307e-01, -1.18728567e-02, ...,
        -6.28244169e-03,  3.31178413e-03,  1.49452025e-02],
       ...,
       [-6.28580922e-02,  6.09366903e-02, -1.62883541e-02, ...,
        -2.46002911e-02,  3.97163834e-03,  1.27984376e-02],
       [ 2.71640766e-02, -7.11689041e-02, -3.19725516e-03, ...,
        -6.21587460e-03,  9.18739049e-03,  8.50802093e-03],
       [-3.08814239e-02,  3.19035871e-02, -5.39471087e-02, ...,
         3.51007945e-02, -1.65756377e-03, -1.68521231e-03]])

In [34]:
sklearn_PCA.explained_variance_ratio_ * 100

array([6.89266892, 5.68841213, 4.53745695, 3.42677135, 3.26430877,
       3.16266067, 2.86252442, 2.12375123, 1.97041337, 1.7831955 ,
       1.64006646, 1.56428622, 1.46274226, 1.44833491, 1.3482858 ,
       1.29516175, 1.24383219, 1.17310333, 1.12105051, 1.07727793,
       0.9925129 , 0.96944916, 0.94252308, 0.90986798, 0.87422391,
       0.84306948, 0.79020494, 0.76321761, 0.73354188, 0.71490557,
       0.69295727, 0.6766773 , 0.65253444, 0.64149409, 0.62269204,
       0.59919615, 0.58808619, 0.57469356, 0.56370274, 0.55340962,
       0.55064115, 0.5400826 , 0.5339106 , 0.5246116 , 0.51019425,
       0.50323242, 0.49588546, 0.47269156, 0.46447523, 0.45652148,
       0.43962447, 0.43294753, 0.43032243, 0.42376213, 0.42021196,
       0.41547342, 0.40669954, 0.40346275, 0.39187399, 0.38874708,
       0.38175932, 0.3755601 , 0.37244005, 0.36591056, 0.35956655,
       0.35522966, 0.34970095, 0.34618228, 0.34047172, 0.33415781,
       0.33098491, 0.32552193, 0.32408451, 0.32104509, 0.3166712 ,
       0.31616911, 0.30996373, 0.30757914, 0.30531764, 0.30395524,
       0.30025585, 0.29890315, 0.29583482, 0.29290687, 0.29078928,
       0.28924684, 0.28708887, 0.28486107, 0.28289354, 0.28066187,
       0.27948942, 0.27696475, 0.27497768, 0.27253819, 0.27239674,
       0.26691595, 0.26484977, 0.26303548, 0.26099544, 0.26066542,
       0.2573836 , 0.25496897, 0.25362125, 0.25195393, 0.25039817,
       0.24845798, 0.2440532 , 0.2421836 , 0.24035358, 0.23843233,
       0.23451796, 0.23116612, 0.23004977, 0.22722331, 0.22561312,
       0.22353257, 0.22146556, 0.22002826, 0.21505531, 0.21366779,
       0.2103356 , 0.20941036, 0.20584206, 0.2041221 , 0.20246881,
       0.198912  , 0.19387625, 0.19196757, 0.1918013 , 0.18793532,
       0.18517133, 0.18141932, 0.17935747, 0.17862128, 0.17539231,
       0.17175293, 0.17071987, 0.16798314, 0.16580816, 0.16186095,
       0.16113931, 0.15770671, 0.15426163, 0.15353826, 0.1496788 ,
       0.14938484, 0.14785221, 0.14282808, 0.14110801, 0.13737644,
       0.13381464, 0.12880306, 0.1269723 , 0.12621309, 0.12072088,
       0.11619156, 0.11433671, 0.11275149, 0.10949846, 0.10586935,
       0.09998981, 0.0989104 , 0.09863567, 0.09545376, 0.09450368,
       0.09114675, 0.08993399, 0.0880872 , 0.08636302, 0.08594232,
       0.08293906, 0.0824035 , 0.07981678, 0.07910577, 0.07786839,
       0.07448096, 0.07242344, 0.07078893, 0.06857806, 0.06720404,
       0.0655648 , 0.06405893, 0.06117639, 0.05858114, 0.05578605,
       0.05451961, 0.05415144, 0.05297882, 0.05212088, 0.05081433,
       0.04925439, 0.04746343, 0.04573825, 0.04523669, 0.04379681,
       0.04200596, 0.04120072, 0.04049974, 0.03967911, 0.03847444])

In [35]:
# getting sum of all variance ratio
sum(sklearn_PCA.explained_variance_ratio_ * 100)

99.16578645500948

### XGBoost

In [38]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [39]:
grid_values = {'n_estimators': [74,75,76], 'learning_rate': [0.15,0.135,0.14], 'max_depth': [1,2,3,4]}
grid_xgb = GridSearchCV(xgb.XGBRegressor(), param_grid = grid_values, cv=10, scoring = 'r2',verbose = True)
grid_xgb.fit(X_train_scalled,y_train)
predict_xgb = grid_xgb.predict(test_scalled)

print('Mean score matrix: ', grid_xgb.cv_results_['mean_test_score'])
print('Grid best parameter (max. accuracy): ', grid_xgb.best_params_)
print('Grid best score (accuracy): ', grid_xgb.best_score_)

Fitting 10 folds for each of 36 candidates, totalling 360 fits
[16:22:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:46] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:47] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:49] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:50] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:51] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:52] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:54] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:22:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

KeyboardInterrupt: ignored

In [40]:
final_predictions = pd.DataFrame()
final_predictions['id'] = test.index
final_predictions['y'] = pd.Series(predict_xgb)
final_predictions.to_csv('predictions.csv', index=False)

NameError: ignored